[core]
    editor = vim
    pager = delta

[interactive]
    diffFilter = delta --color-only

[delta]
    navigate = true
    side-by-side = true
    syntax-theme = Monokai Extended Bright

[merge]
    conflictStyle = diff3

[diff]
    colorMoved = default
