" ****** "
" Vundle "
" ****** "

set nocompatible " be iMproved, required
filetype off     " required

set rtp+=/opt/local/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim' " let Vundle manage Vundle, required
Plugin 'kchmck/vim-coffee-script'
Plugin 'scrooloose/nerdtree'
Plugin 'sickill/vim-monokai'
Plugin 'tpope/vim-rails'
Plugin 'valloric/youcompleteme'
Plugin 'vim-ruby/vim-ruby'

call vundle#end()
filetype plugin indent on

" ************ "
" Key Mappings "
" ************ "

" Alt+\ - show tree
execute "set <M-\\>=\e\\"
noremap <M-\> :NERDTreeToggle<cr>

" ************ "
" Color Scheme "
" ************ "

" Set the color scheme
:if $TERM != 'cygwin' && !empty(glob('~/.vim/bundle/vim-monokai/colors/monokai.vim'))
:  colorscheme monokai
:endif

" Allow syntax highlighting
:syntax on

" ***** "
" Misc. "
" ***** "

" Show line numbers in gutter
:set number

" Set up tab width to be 4 and allow smart indenting
:set tabstop=4
:set shiftwidth=4
:set expandtab
:set smartindent

" Allow the cursor to be placed one character past the end of the line when in view mode
:set virtualedit=onemore

" Show the line and column number at the bottom right of the screen
:set ruler

" Fixes the issue where the `backspace' key was not working in Cygwin
:set bs=2

" Allows left & right arrow keys to wrap across line boundries
:set whichwrap+=<,>,h,l,[,]

" ****************** "
" File Type Settings "
" ****************** "

" Git
autocmd FileType gitcommit setl colorcolumn=50,72
autocmd FileType gitcommit setl spell spelllang=en_us
autocmd FileType gitcommit setl spell spellfile=${HOME}/.vim/en.utf-8.add
